stages:
    - quality
    - build

variables:
    SHOPWARE_VERSION: "6.4.0.0-rc1"
    VERSION_TAG: "6.4.0.0-RC1"

phpstan:
    stage: quality
    image: "edbizarro/gitlab-ci-pipeline-php:7.4"
    before_script:
        - sudo composer self-update --2
    script:
        - git clone -b v${VERSION_TAG} --depth 1 https://github.com/shopware/development "/tmp/shopware"
        - cp -r ${CI_PROJECT_DIR} /tmp/shopware/custom/plugins/${CI_PROJECT_NAME}
        - cd /tmp/shopware/custom/plugins/${CI_PROJECT_NAME} && composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader
        - cd /tmp/shopware && composer install --no-interaction --optimize-autoloader --no-suggest --no-scripts
        - cd /tmp/shopware/custom/plugins/${CI_PROJECT_NAME} && composer phpstan

build:
    stage: build
    image: "dockware/dev:$SHOPWARE_VERSION"
    needs: ["phpstan"]
    only:
        - master
    before_script:
        - sudo rm -rf /var/run/mysqld/mysqld.sock.lock
        - sudo chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
        - sudo service mysql start
    script:
        - 'PACKAGE_VERSION=$(cat composer.json | grep version | head -1 | awk -F: ''{ print $2 }'' | sed ''s/[",]//g'' | tr -d ''[[:space:]]'')'
        - cp -r ${CI_PROJECT_DIR} /var/www/html/custom/plugins/${CI_PROJECT_NAME}
        - cd /var/www/html/custom/plugins/${CI_PROJECT_NAME} && composer install --no-interaction --optimize-autoloader --no-dev
        - cd /var/www/html && php bin/console plugin:refresh -nq && php bin/console plugin:install --activate -c ${CI_PROJECT_NAME} -nq
        - cd /var/www/html && bin/build-administration.sh
        #- cd /var/www/html && bin/build-storefront.sh
        - cd ${CI_PROJECT_DIR} && ls -A1 | xargs rm -rf
        - ls -la ${CI_PROJECT_DIR}
        - cp -r /var/www/html/custom/plugins/${CI_PROJECT_NAME}/* ${CI_PROJECT_DIR}
        - ls -la ${CI_PROJECT_DIR}
    artifacts:
        paths:
            - $CI_PROJECT_DIR/
        name: "saltySw6PerformanceAnalysis"

